Variant Refactor
migueldeicaza/SwiftGodot pull request #199
Opened 2023-10-28 23:44 UTC by PadraigK

Here is some refactoring in advance of adding back the Signal macro. 

The core idea is to leverage the type system a bit more, which lets us reduce the amount of code we're generating and make it possible to use protocols as generic constraints in the Signal macro stuff (coming soon).

By marking all types that can be stored directly in a native Godot `Variant` as `VariantRepresentable` we can add a single `init(_ variant: some VariantRepresentable)` method to `Variant`, instead of needing a separate initializer for each type. This gives us a contract where we (and the type-checker) know that any `VariantRepresentable` type can travel in and out of a Variant. 

Previously this two-way travel worked, but it was not expressed in a way that the type system could reason about it, so we needed to add things like `toVariant()` and an extra protocol to promise that a given type would implement `toVariant()`.

I'll call out some of the good things here:
* `public required init? (_ from: Variant)` is no longer generated on each object, instead the `VariantRepresentable` protocol has a default implementation that can initialize any `VariantRepresentable` from a `Variant`. 
* `public func toVariant () -> Variant` no longer needed and is removed from generation — anything that is `VariantRepresentable` can now initialize a variant using the `init(_ variant: some VariantRepresentable)` initializer.
* Many initializers are removed from `Variant` as they're now handled by `init(_ variant: some VariantRepresentable)`
* Conformances to `VariantRepresentable` and `VariantConvertible` are not code-generated, they're just implemented as extensions. I think this is an improvement because the compiler can tell us about any problems instead of needing to generate the code first. 

And here are some compromises that enable the good things above:
* `init (content: ContentType)` and `init()` are public and required.
* Various ContentType internals are public
* VariantCollection<String> is no longer possible because String is not a direct 1:1 VariantRepresentable type, so these now generate as `VariantCollection<GString>`. There are still conveniences around String ←→ GString, so I am not sure if this is a problem or not.

2023-10-28 23:51 UTC, PadraigK commented
API Diffs here: https://gist.github.com/PadraigK/750bfccd51101109689fbe77edaa0a58

2023-10-29 18:38 UTC, PadraigK commented
Hold off on reviewing/merging this please, I have a couple more improvements that address the compromises above.

2023-10-30 18:22 UTC, PadraigK commented
> Hold off on reviewing/merging this please, I have a couple more improvements that address the compromises above.

Ok, this is in better shape now, it no longer messes up `VariantCollection<String>`

2023-10-30 18:27 UTC, PadraigK commented
Updated Diffs: https://gist.github.com/PadraigK/750bfccd51101109689fbe77edaa0a58

2023-10-31 02:07 UTC, migueldeicaza commented
My initial take is that I like this patch very much.

I would love if you could review the existing documentation in SwiftGodot/Sources/SwiftGodot/SwiftGodot.docc/Variants.md  as part of this PR, to make sure they do not contradict each other.

2023-10-31 02:07 UTC, migueldeicaza requested changes

2023-10-31 02:07 UTC, migueldeicaza commented on Sources/SwiftGodot/Core/VariantRepresentable.swift
> +public protocol VariantRepresentable: VariantStorable {
It would be nice to include a small example here in these API docs.

2023-10-31 02:07 UTC, migueldeicaza commented on Sources/SwiftGodot/Core/VariantStorable.swift
> +public protocol VariantStorable {
For the sake of the public API documentation, let us enumerate in this comment examples of each.

2023-10-31 17:34 UTC, PadraigK commented
> My initial take is that I like this patch very much.
> 
> I would love if you could review the existing documentation in SwiftGodot/Sources/SwiftGodot/SwiftGodot.docc/Variants.md as part of this PR, to make sure they do not contradict each other.

Thanks — I reviewed these and the other two spots you mentioned. Please take another look when you have a chance.

2023-11-01 16:57 UTC, migueldeicaza commented
Thank you for your contribution!

2023-11-01 16:57 UTC, merged

2023-11-01 16:59 UTC, migueldeicaza commented
One question: how does this pass a subclass of Wrapper/Object to a Variant?